### ISSUE TITLE
add_server with weight

### ISSUE THREAD

**Issue by scottrobertson** [subakva/haproxy-tools#12]
Hey,

How would I go about adding a server with weight?

I have the following, but it ignores weight:

```ruby
config  = HAProxy::Config.parse_file('haproxy-starter.cfg')
listen = config.listener('http')
listen.add_server(blah, blah, port: 80, weight: 128)
```

Thanks
Scott

**Comment by scottrobertson** [comment]
If i do:

```listen.add_server(blah, blah, port: 80, attributes: { :weight => 100 })```

I get:

```no implicit conversion of Symbol into String```

**Comment by subakva** [comment]
If you add the attribute names and values as strings, it should work. I'll update the renderer to convert name and value to strings.

**Comment by scottrobertson** [comment]
Perfect, thank you.
