### ISSUE TITLE
specs are broken in rspec 3.0

### ISSUE THREAD

**Issue by drewsonne** [subakva/haproxy-tools#8]
When running the specs the following error is returned:

```
expected true to respond to `true?`
./spec/haproxy/config_spec.rb:27:in `block (3 levels) in <top (required)>'
```

Seems there's a change in rspec >3.0 http://stackoverflow.com/questions/24081843/expected-true-to-respond-to-true

I think specifying some level of version restriction in the gemspec is a decent idea (while leaving it as fluid as possible), so a question to you, are you using rspec ~> 3.0? I'm working on haproxy 1.5 features in a fork.

**Comment by subakva** [comment]
I haven't been actively using haproxy for a while, so haven't been working on this one way or the other. But, I'm using rspec 3 on other projects. I don't have any issue with upgrading to v3 on this one if it makes it easier to work with.

**Comment by drewsonne** [comment]
Cool, thanks. If I get past the work I have to do with the library I might look at refactoring the test cases for rspec 3, but it was more about just getting the tests running. Thanks! :+1:
